version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:dubnium  # primary container for the build job
    steps:
      - checkout
      - run:
          name: "Update NPM"
          command: |
            sudo npm install -g npm@latest
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "Resolve Dependencies"
          command: |
            npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: "Run Node Tests"
          # wait for tunnel listening on port 4445 before running tests
          command: |
            npm install
            npm test
